FROM grafana/grafana:master

MAINTAINER Mikio Nozaki<mikio.nozaki@gmail.com>

EXPOSE 3000

ENV GF_SECURITY_ADMIN_USER admin
ENV GF_SECURITY_ADMIN_PASSWORD password

VOLUME /Users/mickey/Developement/sitespeed-docker/data:/var/lib/grafana
