FROM sitespeedio/graphite:latest

MAINTAINER Mikio Nozaki<mikio.nozaki@gmail.com>

EXPOSE 80 2003

VOLUME /Users/mickey/Developement/sitespeed-docker/data:/opt/graphite/storage/whisper
VOLUME /Users/mickey/Developement/sitespeed-docker/graphite/.htpasswd:/etc/nginx/.htpasswd